name		:=	Brainzz?
compiler	:=	c++
cflags		:=	-Wall -Wextra -Werror -std=c++98



all: $(name)

$(name):
	$(compiler) $(cflags) main.cpp Zombie.cpp newZombie.cpp randomChump.cpp -o $(name)

clean:
	rm $(name)
